// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYKUauzSX7zVPBTt-17tpq_GcKmhUU0tA',
    appId: '1:640779416476:web:874e28083f6438db36ce59',
    messagingSenderId: '640779416476',
    projectId: 'message-reminder-19bbb',
    authDomain: 'message-reminder-19bbb.firebaseapp.com',
    storageBucket: 'message-reminder-19bbb.appspot.com',
    measurementId: 'G-XVZXJSHW5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE7Vt5KkwVlrczTFLHcKVdkxmleO15ziI',
    appId: '1:640779416476:android:eede661dd227357336ce59',
    messagingSenderId: '640779416476',
    projectId: 'message-reminder-19bbb',
    storageBucket: 'message-reminder-19bbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKnFQ-b2ZAtYEI8KY5k4xHmPlW1QbxgCg',
    appId: '1:640779416476:ios:e7feb1c2bc3d60d636ce59',
    messagingSenderId: '640779416476',
    projectId: 'message-reminder-19bbb',
    storageBucket: 'message-reminder-19bbb.appspot.com',
    androidClientId: '640779416476-c9i73ua5f1odspgm70bgk66cq9pvcfsi.apps.googleusercontent.com',
    iosClientId: '640779416476-gupd161ggle4nidi6cp3u05sefbbmitc.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKnFQ-b2ZAtYEI8KY5k4xHmPlW1QbxgCg',
    appId: '1:640779416476:ios:e7feb1c2bc3d60d636ce59',
    messagingSenderId: '640779416476',
    projectId: 'message-reminder-19bbb',
    storageBucket: 'message-reminder-19bbb.appspot.com',
    androidClientId: '640779416476-c9i73ua5f1odspgm70bgk66cq9pvcfsi.apps.googleusercontent.com',
    iosClientId: '640779416476-gupd161ggle4nidi6cp3u05sefbbmitc.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYKUauzSX7zVPBTt-17tpq_GcKmhUU0tA',
    appId: '1:640779416476:web:9ac5f62c9c422f0536ce59',
    messagingSenderId: '640779416476',
    projectId: 'message-reminder-19bbb',
    authDomain: 'message-reminder-19bbb.firebaseapp.com',
    storageBucket: 'message-reminder-19bbb.appspot.com',
    measurementId: 'G-W0LRDR7REN',
  );

}